<?php

namespace AppBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCountriesWithStates(){

		$qb = $this->createQueryBuilder('c')
		           ->select("c")
		           ->addSelect("s")
		           ->addSelect("m")
		           ->leftJoin('c.states', 's')
		           ->leftJoin('s.municipalities', 'm');
		return $qb->getQuery()->getResult();
	}
}
